language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: PM3yVH59uvGd3zHUMEavF3julk4ogqfccCZIQtM/ZVgvashv1LlN5iuLW2VxLvCOcSNBGOqv8qjGm1wOjcnLETNEdq+3CiYF9qz8G6KETlXFSjvUXrvvw4MZEwCL3EqqWGtXLgtH6gXFm35ASqxnuAOrXrHPMCzf14Sn1H1fofFEkoZB8IPhgC9QjitDRtZjJEEdMukLsyNne9nw3/2nu7ZwTE89/BH+IPnk79ZM8h1eayZCpal9aTNwimlDtrCPXUNbJO8Kx4GLXpdyY0WeDRnhhBjoo1wQ1yLru/r61sfTzkbjKxbfB0i2I7ll2FhYNFY2TGFejMWksMZlg6aSlTQGD5OFCPkLq7LXEl6iTEOkLaeicUlynNrxtXZmnVJVh2lxSucPs8LR4JysbuVuIqn22hcmGS7cm4AuHUKt0FxCbXhVFcfi4XeHayR442RpOgN7vgh820cd3toECNQEB2d0IxoKYeRi9xx3/Fsyl0fTkjm+I552lTEhRF33lECuUsA82LAtue2cj7fM0icy/UKB2LAqNYm4W/j3omKA6lWbRNO5cqGHPkJSbFoGNHi3/eec8bz9rNX4YFsYRPE9J5vWrfAs3aI1cTXHa2yNyGmORD+eZkpppYP7O7kgGaic68CuqpmGf4+y7OweJABkZNc58wUybJGaE4S/hSuC9RY=
  app: emojicoat-of-arms
  skip_cleanup: true
  on:
    branch: main
